#!/bin/bash
PEMPATH=~/epaxos/run

ssh -i "$PEMPATH/macbook.pem.txt" 172.31.34.114 "nohup ~/epaxos/bin/master  > ~/master.log 2>&1 &" 
ssh -i "$PEMPATH/macbook.pem.txt" 172.31.34.178 "nohup ~/epaxos/bin/server -$1 -dreply=true   -port 7070  > ~/replica1.log  2>&1  & "
ssh -i "$PEMPATH/macbook.pem.txt" 172.31.35.170 "nohup ~/epaxos/bin/server -$1 -dreply=true  -port 7071  > ~/replica2.log  2>&1  & " 
ssh -i "$PEMPATH/macbook.pem.txt" 172.31.36.122 "nohup ~/epaxos/bin/server -$1 -dreply=true  -port 7072  > ~/replica3.log  2>&1  & "

#ssh -i "$PEMPATH/macbook.pem.txt" 172.31.34.114 "nohup ~/epaxos/bin/master  > ~/master.log 2>&1 &" 
#ssh -i "$PEMPATH/macbook.pem.txt" 172.31.34.178 "nohup ~/epaxos/bin/server -$1 -dreply=false   -port 7070  > ~/replica1.log  2>&1  & "
#ssh -i "$PEMPATH/macbook.pem.txt" 172.31.35.170 "nohup ~/epaxos/bin/server -$1 -dreply=false  -port 7071  > ~/replica2.log  2>&1  & " 
#ssh -i "$PEMPATH/macbook.pem.txt" 172.31.36.122 "nohup ~/epaxos/bin/server -$1 -dreply=false  -port 7072  > ~/replica3.log  2>&1  & "


